<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pluto</string>
		<string>lua</string>
	</array>
	<key>firstLineMatch</key>
	<string>\A#!.*?\bpluto(\d+(\.\d+)?)?\b|\A--\s+-\*-\s*pluto\s*-\*-</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Pluto</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#pluto</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>pluto</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(function)\s*(?:[a-zA-Z_][a-zA-Z0-9_]*([\.:]))?([a-zA-Z_][a-zA-Z0-9_]*)?\s*(\()?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.pluto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameter.pluto</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.pluto</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.group.begin.pluto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.group.end.pluto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.pluto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z_][a-zA-Z0-9_]*</string>
							<key>name</key>
							<string>variable.parameter.function.pluto</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.comma.pluto</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\.\.\.</string>
							<key>name</key>
							<string>constant.language.pluto</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.pluto</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=[,\)])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#pluto</string> <!-- not using simpleexp because default arguments uses 'expr' (indirectly, causing unary + and - to be available.) --> 
								</dict>
							</array>
							<key>name</key>
							<string>meta.default-arguments.pluto</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#simpleexp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.group.begin.pluto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.group.end.pluto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function-call.pluto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.comma.pluto</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pluto</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\.cdef)\s*(\[(=*)\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.other.multiline.pluto</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.pluto</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.pluto</string>
					<key>end</key>
					<string>(\]\2\])</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.other.multiline.pluto</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.pluto</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!--)\[(=*)\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.pluto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]\1\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.pluto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.multiline.pluto</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.pluto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\A(#!).*$\n?</string>
					<key>name</key>
					<string>comment.line.shebang.pluto</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>--\[(=*)\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.pluto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]\1\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.pluto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.pluto</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>--</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.pluto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-dash.pluto</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goto.pluto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.placeholder.pluto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(goto)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.label.begin.pluto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.label.end.pluto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(::)[a-zA-Z_][a-zA-Z0-9_]*(::)</string>
					<key>name</key>
					<string>constant.other.placeholder.pluto</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.pluto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.pluto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b((?:pluto_)?class)\s+([a-zA-Z_][a-zA-Z0-9_]*)?</string>
					<key>name</key>
					<string>meta.class.pluto</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.enum.pluto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.pluto</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.enum.pluto</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.control.pluto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b((?:pluto_)?enum(?:\s+class)?)(?:\s+(begin)|(?:\s+([a-zA-Z_][a-zA-Z0-9_]*)?)(?:\s+(begin))?)?</string>
					<key>name</key>
					<string>meta.enum.pluto</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.extends.pluto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.pluto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(extends)\s+([a-zA-Z_][a-zA-Z0-9_]*)?</string>
					<key>name</key>
					<string>constant.other.placeholder.pluto</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.pluto</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.class.pluto</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(new)\s+([a-zA-Z_][a-zA-Z0-9_]*)?</string>
					<key>name</key>
					<string>meta.instantiation.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(break|continue|do|else|for|if|elseif|goto|return|switch|pluto_switch|then|repeat|while|until|end|in|as|case|default|begin)\b</string>
					<key>name</key>
					<string>keyword.control.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(local|static|export|pluto_export)\b</string>
					<key>name</key>
					<string>storage.modifier.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![^.]\.|:)\b(false|nil|true)\b|(?&lt;![.])\.\.\.(?!\.)</string>
					<key>name</key>
					<string>constant.language.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![^.]\.|:)\b(_G|_VERSION|_PVERSION|_PSOUP|math\.(pi|huge))\b</string>
					<key>name</key>
					<string>support.constant.builtin.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![^.]\.|:)\b(self)\b</string>
					<key>name</key>
					<string>variable.language.self.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![^.]\.|:)\b((pluto_)?parent)\b</string>
					<key>name</key>
					<string>variable.language.parent.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![^.]\.|:)\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall)\b(?=\s*(?:[({"']|\[\[))</string>
					<key>name</key>
					<string>support.function.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(coroutine|package|string|utf8|table|math|io|os|debug)\b</string>
					<key>name</key>
					<string>support.function.library.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|or|not|instanceof)\b</string>
					<key>name</key>
					<string>keyword.operator.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([a-zA-Z_][a-zA-Z0-9_]*)\b(?=\s*(?:[({"']|\[\[))</string>
					<key>name</key>
					<string>support.function.any-method.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[^.]\.|:)\b([a-zA-Z_][a-zA-Z0-9_]*)</string>
					<key>name</key>
					<string>variable.other.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|-|%|#|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)|\?\.?|\:=|\$|\||~</string>
					<key>name</key>
					<string>keyword.operator.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\.\b</string>
					<key>name</key>
					<string>punctuation.accessor.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.pluto</string>
				</dict>
			</array>
		</dict>
		<key>simpleexp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w\d.])0[xX][0-9A-Fa-f]+(?![pPeE.0-9])</string>
					<key>name</key>
					<string>constant.numeric.integer.hexadecimal.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w\d.])0[xX][0-9A-Fa-f]+(\.[0-9A-Fa-f]+)?([eE]-?\d*)?([pP][-+]\d+)?</string>
					<key>name</key>
					<string>constant.numeric.float.hexadecimal.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w\d.])\d+(?![pPeE.0-9])</string>
					<key>name</key>
					<string>constant.numeric.integer.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w\d.])\d+(\.\d+)?([eE]-?\d*)?</string>
					<key>name</key>
					<string>constant.numeric.float.pluto</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.pluto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.pluto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.pluto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.pluto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.pluto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.pluto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.table.begin.pluto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.table.end.pluto</string>
						</dict>
					</dict>
					<key>name</key>
					<string>table.pluto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#pluto</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[abfnrtvz\\"'\n]</string>
					<key>name</key>
					<string>constant.character.escape.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\d{1,3}</string>
					<key>name</key>
					<string>constant.character.escape.byte.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\x[0-9A-Fa-f][0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.character.escape.byte.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u\{[0-9A-Fa-f]+\}</string>
					<key>name</key>
					<string>constant.character.escape.unicode.pluto</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.character.escape.pluto</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pluto</string>
	<key>uuid</key>
	<string>39640FE2-5354-4838-B02A-712D069BA69A</string>
</dict>
</plist>
